GET http://localhost:3333/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDgxNjQ1NS1kZjNjLTRhM2UtOTgwYi03MWUwZGJjZDYzNjQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc3Njk3MjMxNX0.2wFuFL-LGjrQX9b015xSxVMHxej392x7lpr6PPz_Smc

###

POST http://localhost:3333/courses
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDgxNjQ1NS1kZjNjLTRhM2UtOTgwYi03MWUwZGJjZDYzNjQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc3Njk3MjMxNX0.2wFuFL-LGjrQX9b015xSxVMHxej392x7lpr6PPz_Smc

{ 
  "title": "Curso de Java + spring boot" 
}

###

GET http://localhost:3333/courses/882e1fcd-45c8-4f3c-974f-41e5104b861f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjMDgxNjQ1NS1kZjNjLTRhM2UtOTgwYi03MWUwZGJjZDYzNjQiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc3Njk3MjMxNX0.2wFuFL-LGjrQX9b015xSxVMHxej392x7lpr6PPz_Smc
###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Salvador4@live.com",
  "password": "123456"
}