GET http://localhost:3333/courses

###

POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTEyZWFiZi1hOTFjLTRmODctOTkzYS1mNzMxZjg2N2M0N2UiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3NjkwMzcwOX0.8DpiyJM-YPGiAtXtzWeUgJfP4eJC7wdsaVMWXv9JVKI

{ 
  "title": "Curso de Java + spring boot" 
}

###

GET http://localhost:3333/courses/0b135d58-2335-4251-8a03-7b887aaabbde
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTEyZWFiZi1hOTFjLTRmODctOTkzYS1mNzMxZjg2N2M0N2UiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc3NjkwMzcwOX0.8DpiyJM-YPGiAtXtzWeUgJfP4eJC7wdsaVMWXv9JVKI

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "geraldinhoMCR@hotmail.com",
  "password": "123456"
}